apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-auth
  labels:
    app: pcc-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcc-auth
  template:
    metadata:
      labels:
        app: pcc-auth
    spec:
      containers:
        - name: pcc-auth
          image: diogojms/pcc_auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/User"
            - name: SECRET
              value: "jfcnbjsnwdelwjcnewdlejbsfew"
            - name: LOGS_URI
              value: "guest:guest@localhost:5672/"
