apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-project
  labels:
    app: scc-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scc-project
  template:
    metadata:
      labels:
        app: scc-project
    spec:
      containers:
      - name: scc-project
        image: diogojms/scc_project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: MONGODB_URI
            value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/User"
          - name: SECRET
            value: "jfcnbjsnwdelwjcnewdlejbsfew"
          - name: LOGS_URI
            value: "guest:guest@localhost:5672/"