version: "3"

services:
  api-auth:
    build:
      context: ./api-auth
      dockerfile: Dockerfile
    command: npm start
    container_name: DriveCleaner
    volumes:
      - ./api-auth:/usr/src/app
    restart: always
    ports:
      - "27017:27017"
    networks:
      - api-auth-network
    environment:
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_NAME: DriveCleaner
      DATABASE_USER: DriverCleaner
      DATABASE_PASSWORD: DriverCleanerG7
      APP_PORT: 27017
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

networks:
  name: api-auth-network
  driver: bridge
