apiVersion: v1
kind: Service
metadata:
  name: pcc-auth
  labels:
    app: pcc-auth
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: pcc-auth
  sessionAffinity: None
