apiVersion: v1
kind: Service
metadata:
  name: scc-project
  labels:
    app: scc-project
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: scc-project
  sessionAffinity: None